coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 2%
        base: auto
        paths:
          - "sieve"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
